---
- name: Create .hushlogin
  file:
    path: /root/.hushlogin
    state: touch

- name: Edit PS1 variable
  lineinfile:
    path: /etc/profile
    line: PS1='[\h] \[\033[1;33m\]~\[\033[0m\] '

- name: Extend history length
  lineinfile:
    path: /etc/profile
    line: "{{ item }}"
  with_items:
    - "export HISTSIZE=10000"
    - "export HISTFILESIZE=10000"