---
- name: Disable enterprise repository
  replace:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^(\s?deb) (.*?)'
    replace: '# deb \2'

- name: Add no-subscription repository
  lineinfile:
    path: /etc/apt/sources.list
    line: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
    state: present

- name: Disable enterprise ceph repository
  replace:
    path: /etc/apt/sources.list.d/ceph.list
    regexp: '^(\s?deb) (.*?)'
    replace: '# deb \2'

- name: Add no-subscription ceph repository
  lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    line: deb http://download.proxmox.com/debian/ceph-reef bookworm no-subscription
    state: present