- name: Ensure pip
  apt:
    name: python3-pip
    state: present

- name: Ensure proxmoxer
  apt:
    name: python3-proxmoxer
    state: present

- name: Ensure requests
  apt:
    name: python3-requests
    state: present

- name: Create new VM
  proxmox_kvm:
    agent: yes
    api_host: "{{ api_host }}"
    api_user: "{{ api_rw_user }}"
    api_token_id: "{{ api_rw_token_id }}"
    api_token_secret: "{{ api_rw_token_secret }}"
    autostart: true
    balloon: 4096
    bios: seabios
    boot: 'order=ide0;scsi0;net0'
    bootdisk: scsi0
    clone: FEDORA-DOCKER-TEMPLATE01
    cores: 2
    cpu: host
    full: true
    kvm: true
    machine: q35
    memory: 4096
    name: "{{ VMName | upper }}"
    net:
      net0: 'virtio,bridge=vmbr0,tag=100,firewall=0'
    newid: "{{ VMID }}"
    node: "{{ api_host }}"
    onboot: true
    ostype: l26
    scsi:
      scsi0: "data-images:20,format=raw"
    scsihw: virtio-scsi-single
    sockets: 1
    state: present
    timeout: 1000
  register: new_vm
  notify: 
    - Start VM
    - Add static DHCP entry
    # - Add alias